#!/usr/bin/env bash


# color formatiing
BOLD_SUCCESS=$'\033[1;32m'
RESET_FORMATTING=$'\033[0m'


# clean existing config files
# kde plasma
rm -f  \
    "$HOME"/.config/breezerc \
    "$HOME"/.config/dolphinrc \
    "$HOME"/.config/kcminputrc \
    "$HOME"/.config/kdeglobals \
    "$HOME"/.config/kglobalshortcutsrc \
    "$HOME"/.config/kiorc \
    "$HOME"/.config/klaunchrc \
    "$HOME"/.config/krunnerrc \
    "$HOME"/.config/ksplashrc \
    "$HOME"/.config/ktimezonedrc \
    "$HOME"/.config/kwinrc \
    "$HOME"/.config/kxkbrc \
    "$HOME"/.config/plasma-org.kde.plasma.desktop-appletsrc \
    "$HOME"/.config/plasmarc \
    "$HOME"/.config/plasmashellrc \
    "$HOME"/.config/spectaclerc \
    "$HOME"/.config/systemsettingsrc

# kitty
rm -rf "$HOME"/.config/kitty

# code
rm -rf \
    "$HOME"/.config/Code/User/keybindings.json \
    "$HOME"/.config/Code/User/settings.json

# stow config files
stow kde
stow kitty
stow code
stow scripts

# clean plasma cache
rm -rf "$HOME"/.cache/*

printf '\n%sConfiguration files setup is finished!%s' \
    "$BOLD_SUCCESS" "$RESET_FORMATTING"
