#!/usr/bin/env bash


# color formatting
BOLD_WARNING=$'\033[1;33m'
BOLD_SUCCESS=$'\033[1;32m'
RESET_FORMATTING=$'\033[0m'


# body
printf '\n%sConfiguration files setup was started!%s' \
    "$BOLD_WARNING" "$RESET_FORMATTING"

# stow config files
stow --adopt \
    applications \
    code \
    fonts \
    kde \
    kitty \
    system-scripts \
    wallpapers

# discard adopted changes
git restore .

# update applications database with new entries
update-desktop-database "$HOME"/.local/share/applications

# install custom font files
fc-cache -f

# clean plasma cache
rm -rf "$HOME"/.cache/*

printf '\n%sConfiguration files setup is finished.%s' \
    "$BOLD_SUCCESS" "$RESET_FORMATTING"

sleep 5;
reboot
