# kitty configuration

# customization
# themes

# BEGIN_KITTY_THEME
# Pnevma
include current-theme.conf
# END_KITTY_THEME

# font
font_family family="IBM Plex Mono"
bold_font auto
italic_font auto
bold_italic_font auto
font_size 10.0

# cursor
cusor_shape beam
cusor_blink_interval 0 # seconds
cursor_stop_blinking 0 # seconds

# scrollback
scrollback_lines 1000

# window layout
remember_window_size no
initial_window_width 800
initial_window_height 500
window_border_width 1.0pt
enabled_layouts tall
window_padding_width 2
window_margin_width 1
hide_window_decorations no

# tab layout
tab_bar_style powerline
tab_powerline_style slanted
tab_bar_edge bottom
tab_bar_align left
active_tab_font_style   bold
inactive_tab_font_style normal

# shortcuts
# window management
map ctrl+n new_window

# tab management
map ctrl+t new_tab
map ctrl+shift+k new_tab_with_cwd
map ctrl+[ previous_tab
map ctrl+] next_tab
map ctrl+w close_tab
map alt+left move_tab_backward
map alt+right move_tab_forward

# overall usage
map ctrl+shift+c copy_to_clipboard
map ctrl+v paste_from_clipboard
