'''
Theming
'''

# shell
background #1c1c1c
foreground #d9daca

# cursor and fonts
cursor #e3c8ae
color0 #2f2e2d
color8 #4a4845
color1 #a36666
color9 #d78787
color2 #90a57d
color10 #afbea2
color3 #d7af87
color11 #e4c9af
color4 #7fa5bd
color12 #a1bdce
color5 #c79ec4
color13 #d7beda
color6 #8adbb4
color14 #b1e7dd
color7 #d0d0d0
color15 #efefef

# selection
selection_background #818e77
selection_foreground #131313

# url
url_color #a7b95a

# inner window border
active_border_color #90a57d
inactive_border_color #414141

# tab bar
active_tab_background #5a5b54
active_tab_foreground #e3c8ae
inactive_tab_background #2d2c2c
inactive_tab_foreground #d0d0d0


'''
Emulator customization
'''

# advanced
allow_remote_control no
notify_on_cmd_finish unfocused 15.0 bell
allow_hyperlinks yes

# font
font_family IBM Plex Mono
bold_font auto
italic_font auto
bold_italic_font auto
font_size 9.5

# cursor
shell_integration no-cursor
cursor_shape beam
cursor_shape_unfocused underline

# cursor style
cursor_beam_thickness 1.8
cursor_underline_thickness 1.5
cursor_blink_interval 0

# scrollback
scrollback_lines 1000
scrollbar hovered
scrollbar_interactive yes
scrollbar_jump_on_click yes

# scrollbar style
scrollbar_width 0.4
scrollbar_hover_width 0.8
scrollbar_handle_opacity 0.3

# progress bar
progress_bar bottom

# url
url_style dotted
detect_urls yes

# hyperlink
show_hyperlink_targets always
underline_hyperlinks hover

# window layout
remember_window_size no
hide_window_decorations no
initial_window_width 800
initial_window_height 500
enabled_layouts tall
placement_strategy center

# window layout style
window_margin_width 2 2 2 2
window_padding_width 5 5 5 5
window_border_width 1.1

# tab bar
tab_bar_edge bottom
tab_bar_style powerline
tab_bar_align left

# tab bar style
tab_powerline_style slanted
tab_title_max 25
active_tab_font_style bold
inactive_tab_font_style normal
tab_bar_margin_color none

# background style
background_opacity 0.92
background_blur 1


'''
Keyboard shortcuts
'''

# clear default shortcuts
clear_all_shortcuts yes

# window management
map ctrl+t new_window
map ctrl+w close_window
map ctrl+shift+k new_window_with_cwd
map ctrl+pagedown previous_window
map ctrl+pageup next_window
map ctrl+shift+pagedown move_window_backward
map ctrl+shift+pageup move_window_forward

# tab management
map ctrl+shift+t new_tab
map ctrl+shft+w close_tab
map ctrl+[ previous_tab
map ctrl+] next_tab
map ctrl+shfit+[ move_tab_backward
map ctrl+shfit+] move_tab_forward

# font sizes
map ctrl+equal change_font_size all +0.5
map ctrl+minus change_font_size all -0.

# miscellaneous
map ctrl+, edit_config_file
map ctrl+shift+c copy_to_clipboard
map ctrl+v paste_from_clipboard
